### PR TITLE
Updated ColorInputWidget to have both editable hex field and color selector

### PR DESCRIPTION
**Pull request by marts**
Hi @marteinn, I've made a small update to your wagtail color panel to allow color values to be entered manually, as well as the using the color input selector. If the text input changes, the color should also change and vice versa.

Hope you like it :)

Screenshot 2021-01-09 at 16 41 13

### CODE REVIEW

**Comment by marteinn** [comment]
Thanks for the PR @marts, this a great addition to the library!

I think you have done a fine job, it's a simple and clear solution (also thanks for cleaning up some of my commented code). I've merged this with a slight change where I expand the input field on mobile devices, I also changed the classes to follow a BEM pattern. (You can see my changes here: https://github.com/marteinn/wagtail-color-panel/commit/7c3182ea41d4241cd980cd15ce5de4ee9a219a41)

**Comment by marteinn** [comment]
Also many thanks for the attached screenshot in the PR, it makes my life so much easier :)

**Comment by marteinn** [comment]
FYI: I've just released 1.2.0 with this PR included.

**Comment by marts** [comment]
Excellent, thanks for this. I'm planning on using it for a plotly based wagtail chart package I'm building.

**Comment by marteinn** [comment]
@marts Sounds interesting! Please let me know when you have something to show :)

**Comment by marts** [comment]
Hi @marteinn, just to let you know I've pushed my first installment of `wagtail-plotly` that uses your color picker. Still very much work in progress ... https://github.com/cursive-works/wagtail-plotly

**Comment by marteinn** [comment]
@marts Awesome, looks promising!

**Pull request merged**
