### PR TITLE
Wagtail >= 5.0 support

### PR DESCRIPTION
**Pull request by katdom13**
## Wagtail 5.0 [See release notes](https://docs.wagtail.org/en/stable/releases/5.0.html)

- Updated documentation and tests to support Django 4.2 and Wagtail 5.0

## Wagtail 5.1 [See release notes](https://docs.wagtail.org/en/stable/releases/5.1.html)

- Updated documentation and tests to support Wagtail 5.1

## Wagtail 5.2 [See release notes](https://docs.wagtail.org/en/stable/releases/5.2.html)

- Update test matrix to include Wagtail 5.2

### CODE REVIEW

**Comment by marteinn** [comment]
Hi @katdom13 and thanks for the PR! This project uses git-flow so please use the `develop` branch when creating PR:s, thanks!

**Comment by katdom13** [comment]
Hi @marteinn ,
Changed target to `develop`

**Comment by marteinn** [comment]
Excellent @katdom13  👍 Will review your code this weekend

**Comment by marteinn** [comment]
This PR has been merged and released as v1.5.0, thank you so much @katdom13!

**Pull request merged**
